services:
  ia_l0st:
    hostname:         ia_l0st.innovanon.com
    build:
      context:        .
      tags:
        - innovanon/ia_l0st:latest
        -           ia_l0st:latest
        - innovanon/ia_l0st
        -           ia_l0st
    image:            innovanon/ia_l0st
    restart:          no
    logging:
      driver:         syslog   
